version: '3'

services:
  server:
    build:
      context: ./image
    volumes:
      - .:/workspace
      - python-cache:/home/worker/.local/share
    command: sphinx-autobuild --delay 3 --host 0.0.0.0 . _build
    ports:
      - 8000:8000

volumes:
  python-cache:
